# Generated by Django 6.0.2 on 2026-06-22 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gryphon_playground", "0001_initial"),
        ("tap_grid", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpgcyclenode",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tap_grid.entity",
            ),
        ),
        migrations.AddField(
            model_name="historicalpgcyclenode",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalpghub",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tap_grid.entity",
            ),
        ),
        migrations.AddField(
            model_name="historicalpghub",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalpgleaf",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tap_grid.entity",
            ),
        ),
        migrations.AddField(
            model_name="historicalpgleaf",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalpgnode",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tap_grid.entity",
            ),
        ),
        migrations.AddField(
            model_name="historicalpgnode",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pgcyclenode",
            name="entity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
            ),
        ),
        migrations.AddField(
            model_name="pghub",
            name="entity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
            ),
        ),
        migrations.AddField(
            model_name="pgleaf",
            name="entity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
            ),
        ),
        migrations.AddField(
            model_name="pgnode",
            name="entity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
            ),
        ),
    ]
