# Generated by Django 6.0.2 on 2026-07-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gryphon_playground", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pgcyclenode",
            table="gryphon_playground__pg_cycle_node",
        ),
        migrations.AlterModelTable(
            name="pghub",
            table="gryphon_playground__pg_hub",
        ),
        migrations.AlterModelTable(
            name="pgleaf",
            table="gryphon_playground__pg_leaf",
        ),
        migrations.AlterModelTable(
            name="pgnode",
            table="gryphon_playground__pg_node",
        ),
    ]
