# Generated by Django 6.0.2 on 2026-07-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gryphon_playground", "0003_alter_pgcyclenode_table_alter_pghub_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpghub",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalpghub",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalpgleaf",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalpgleaf",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalpgnode",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalpgnode",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="pgcyclenode",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="pghub",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="pgleaf",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="pgnode",
            name="entity",
        ),
        migrations.DeleteModel(
            name="HistoricalPgCycleNode",
        ),
        migrations.DeleteModel(
            name="HistoricalPgHub",
        ),
        migrations.DeleteModel(
            name="HistoricalPgLeaf",
        ),
        migrations.DeleteModel(
            name="HistoricalPgNode",
        ),
        migrations.DeleteModel(
            name="PgCycleNode",
        ),
        migrations.DeleteModel(
            name="PgHub",
        ),
        migrations.DeleteModel(
            name="PgLeaf",
        ),
        migrations.DeleteModel(
            name="PgNode",
        ),
    ]
